
#   ____                                      
#  / ___|___  _ __ ___  _ __ ___   ___  _ __  
# | |   / _ \| '_ ` _ \| '_ ` _ \ / _ \| '_ \ 
# | |__| (_) | | | | | | | | | | | (_) | | | |
#  \____\___/|_| |_| |_|_| |_| |_|\___/|_| |_|
 
[agents]
# Settings shared by all agents
frontend_address = "tcp://localhost:9090"
backend_address = "tcp://localhost:9091"
settings_address = "tcp://localhost:9092"
compress = true
timecode_fps = 20

#  __  __                   _ _ _   _     _      
# |  \/  | ___  _ __   ___ | (_) |_| |__ (_) ___ 
# | |\/| |/ _ \| '_ \ / _ \| | | __| '_ \| |/ __|
# | |  | | (_) | | | | (_) | | | |_| | | | | (__ 
# |_|  |_|\___/|_| |_|\___/|_|_|\__|_| |_|_|\___|
#                                                

[broker]
frontend_address = "tcp://*:9090"
backend_address = "tcp://*:9091"
settings_address = "tcp://*:9092"

[feedback]
sub_topic = ["GUI"]
print_width = 0
indent_width = 2

[bridge]
# default publish topic (if not passed via CLI)
sub_topic = ["publish"]
pub_topic = "bridge"

[metadata]
# Topic to publish to (single string!)
pub_topic = "metadata"

[perf_assess]
pub_topic = "perf_assess"

[publish]
pub_topic = "publish"

[dealer]
sub_topic = ["publish", "spawner"]
pub_topic = "dealer"
dealer_address = "tcp://*:9093"

[worker]
pub_topic = "worker"
dealer_address = "tcp://localhost:9093"

[monitor]
sub_topic = [""]

#  ____  _             _           
# |  _ \| |_   _  __ _(_)_ __  ___ 
# | |_) | | | | |/ _` | | '_ \/ __|
# |  __/| | |_| | (_| | | | | \__ \
# |_|   |_|\__,_|\__, |_|_| |_|___/
#                |___/             
#

[tui]
pub_topic = "metadata" # NOTHE THIS!!!
silent = false # Avoids polluting the console with debug messages


[echoj]
# Topic to publish to (single string!)
pub_topic = "echoj"
sub_topic = ["rfid"]

[clock]
# Topic to publish to (single string!)
pub_topic = "clock"
period = 200

[loadcells]
period = 18
pub_topic = "loadcells"
show_void_phidget = true
[loadcells.serial_number]
mono = 588716
triaxis_l = 582396
triaxis_r = 588795

[driver]
sub_topic = "FSM/set_point"
speed_limit = 30.5
wheel_radius = 0.084
port = "/dev/drivers"
dont_block = true
period = 8
queue_size = 1

[ego_state]
sub_topic = ["driver", "forces_calibrated", "FSM/odometry", "calibrated_imu", "htc"]
pub_topic = "ego_state"
dead_zone_F = 1000
dead_zone_T = 0.3
wheel_radius = 0.084
wheel_base = 0.86
total_ticks_enc = 4096
dist_bar_3LC_x = 0.38
dist_bar_3LC_y = 0.17
dist_bar_side_x = 0.183
dist_bar_side_y = 0.335
angles_load_cells = 0.785375
[ego_state.imu]
sigma_gyro = 0.2
sigma_accel = 0.05
sigma_magnet = 25
dist_y = -0.20
dist_x = 0.7
imu_enable = true

[forces_calibration]
sub_topic = ["loadcells", "GUI", "autocalibration"]
pub_topic = "forces_calibrated"

[FSM]
sub_topic = ["ego_state", "GUI", "driver", "unhookdetector"]
pub_topic = "FSM/set_point"
time_slipping = 1.5
time_unhook = 0.5
silent = false
[FSM.impedance_control]
wheel_radius = 0.084
wheel_base = 0.86
walker_mass = 59
wheel_mass = 1
I_body = 30.5
[FSM.set_reference]
delta_s = 1.0

[portenta]
sub_topic = ["FSM/portenta"]
port = "/dev/portenta"
silent = false

[hat]
pub_topic = "imu"
period = 20
[hat.enabled_sensors]
gyro = true
humidity = false
pressure = false
compass = true

[agents_status]
silent = true
sub_topic = ["agent_event"]

[GUI_EVENT]
pub_topic = "GUI"
sub_topic = ["FSM/mode", "watchdog"]

[GUI_HF]
pub_topic = "GUI"
sub_topic = ["FSM/path_planning", "driver"]

[GAME_EVENT]
pub_topic = "GAME"
sub_topic = ["watchdog","GUI","FSM/mode"]

[GAME_HF]
pub_topic = "GAME"
sub_topic = ["FSM/path_planning"]

[watchdog]
period = 2000

[walker_inertia]
sub_topic = ["imu"]
period = 500
wheel_radius = 0.084
wheel_base = 0.86

[walker_dumping]
sub_topic = ["imu"]
wheel_radius = 0.084
wheel_base = 0.86

[htc]
file_path="/home/miro/config_files/survive_mapping.json"
silent=true 
period=100

[path_following_requirement_test]
sub_topic = ["FSM/path_planning", "FSM/mode"]

[imu_calibration]
pub_topic = "calibrated_imu"
sub_topic = ["GUI", "imu"]
num_cycles = 2
n_samples = 300
silent = false

[unhookdetector]
sub_topic = ["forces_calibrated"]
threshold = 0.08 
k = 3            
window_size = 50 
n = 3           
load_cell_names = ["back_left", "back_right", "front_left", "front_right"]

[test_clothoid_path_follow]
sub_topic = ["ego_state", "FSM/path_planning", "FSM/mode", "driver"]