#   ____
#  / ___|___  _ __ ___  _ __ ___   ___  _ __
# | |   / _ \| '_ ` _ \| '_ ` _ \ / _ \| '_ \
# | |__| (_) | | | | | | | | | | | (_) | | | |
#  \____\___/|_| |_| |_|_| |_| |_|\___/|_| |_|
#


[agents]
# Settings shared by all agents
frontend_address = "tcp://raspberrypi:9090"
backend_address = "tcp://raspberrypi:9091"
settings_address = "tcp://raspberrypi:9092"
timecode_fps = 25


#  __  __                   _ _ _   _     _
# |  \/  | ___  _ __   ___ | (_) |_| |__ (_) ___
# | |\/| |/ _ \| '_ \ / _ \| | | __| '_ \| |/ __|
# | |  | | (_) | | | | (_) | | | |_| | | | | (__
# |_|  |_|\___/|_| |_|\___/|_|_|\__|_| |_|_|\___|
#

[broker]
frontend_address = "tcp://*:9090"
backend_address = "tcp://*:9091"
settings_address = "tcp://*:9092"
prefer_loopback_for_local_services = true
# The followings are only needed if using CURVE encryption
# auth_verbose = false
# ip_whitelist = ["127.0.0.1"] # default is empty (allow all)

[logger]
mongo_uri = "mongodb://localhost:27017"
mongo_db = "mads_test"
# sub_topic = ["logger", "metadata", "rfid", "skeleton", "platform", "image", "agent_event", "bridge", "perf_assess"]
sub_topic = ["harness_detachment"]
# or, subscribe to all topics:
#sub_topic = [""]
max_length = 75
initially_paused = false

[metadata]
# Topic to publish to (single string!)
pub_topic = "metadata"

[perf_assess]
pub_topic = "perf_assess"

[dealer]
sub_topic = ["publish", "spawner"]
pub_topic = "dealer"
dealer_address = "tcp://*:9093"

[worker]
pub_topic = "worker"
dealer_address = "tcp://localhost:9093"


#  ____  _             _
# |  _ \| |_   _  __ _(_)_ __  ___
# | |_) | | | | |/ _` | | '_ \/ __|
# |  __/| | |_| | (_| | | | | \__ \
# |_|   |_|\__,_|\__, |_|_| |_|___/
#                |___/
#


[bridge]
# default publish topic (if not passed via CLI)
sub_topic = ["publish"]
pub_topic = "bridge"

[publish]
pub_topic = "publish"

[feedback]
# Subscribes to ALL topics
sub_topic = [""]
print_width = 0
indent_width = 2

[monitor]
sub_topic = [""] # Subscribe to all topics
col_widths = [18, 15, 15] # Widths of first three columns
yellow = 0.1 # seconds: color yellow periods larger than that
red = 0.1    # seconds: color red periods larger than that
silent = true

[replay]
db_uri = "mongodb://localhost:27017"
db_name = "mads_test"                                      # Mandatory, a string
collections = ["perf_assess_1", "perf_assess_2"]   # Mandatory, array of strings
start_time = "2026-03-10T20:27:00Z"      # Mandatory, a string in ISO8601 format
end_time = "2026-03-10T20:27:10Z"        # Mandatory, a string in ISO8601 format
max_loop_duration_ms = 0
repeat = false
view_name = "mads_replay_view"   # default="": if specified mongo_replay creates
                                 # a view with this name 
reuse_view = false         # default=false: if true and view_name is specified, 
                           # mongo_replay will reuse the existing view

[rerunner_detectors]
sub_topic = ["ego_state","unhookdetector"]
time = "/timecode"
keypaths = ["/ego_state/slipping_detection","/unhookdetector/si"]
blueprint = "blueprints/detectors.rbl"
queue_size = 1

[ego_state_trajectory]
sub_topic = ["ego_state"]

[rerunner_loadcells]
sub_topic = ["loadcells"]
time = "/timecode"
keypaths = ["/loadcells/forces/mono/back_left", "/loadcells/forces/mono/back_right", "/loadcells/forces/mono/front_left", "/loadcells/forces/mono/front_right", "/loadcells/forces/triaxis_l/fx_l", "/loadcells/forces/triaxis_l/fy_l", "/loadcells/forces/triaxis_l/fz_l", "/loadcells/forces/triaxis_r/fx_r", "/loadcells/forces/triaxis_r/fy_r", "/loadcells/forces/triaxis_r/fz_r"]
blueprint = "blueprints/loadcells.rbl"
queue_size = 1

[rerunner_forces_calibrated]
sub_topic = ["forces_calibrated"]
time = "/timecode"
keypaths = ["/forces_calibrated/forces/mono/back_left", "/forces_calibrated/forces/mono/back_right", "/forces_calibrated/forces/mono/front_left", "/forces_calibrated/forces/mono/front_right", "/forces_calibrated/forces/triaxis_l/fx_l", "/forces_calibrated/forces/triaxis_l/fy_l", "/forces_calibrated/forces/triaxis_l/fz_l", "/forces_calibrated/forces/triaxis_r/fx_r", "/forces_calibrated/forces/triaxis_r/fy_r", "/forces_calibrated/forces/triaxis_r/fz_r"]
blueprint = "blueprints/forces_calibrated.rbl"
queue_size = 1

[rerunner_calibrated_imu]
sub_topic = ["calibrated_imu"]
time = "/timecode"
keypaths = ["/calibrated_imu/acc_x", "/calibrated_imu/acc_y","/calibrated_imu/gyro"]
blueprint = "blueprints/calibrated_imu.rbl"
queue_size = 1

[rerunner_imu]
sub_topic = ["imu"]
time = "/imu/timecode"
queue_size = 1
keypaths = ["/imu/accel/0", "/imu/accel/1", "/imu/accel/2", "/imu/gyro/0", "/imu/gyro/1", "/imu/gyro/2"]
blueprint = "blueprints/imu.rbl" #Relativo rispetto a dove viene lanciato il comando

[rerunner_driver]
sub_topic = ["driver", "calculated_torque", "FSM/set_point"]
time = "/driver/timecode"
keypaths = ["/driver/encoders/left", "/driver/encoders/right", "/driver/speeds/left", "/driver/speeds/right", "/driver/currents/right", "/driver/currents/left", "/driver/voltage", "/driver/issue", "/calculated_torque/torque/right_calculated", "/calculated_torque/torque/left_calculated", "FSM/set_point/sp/dx", "FSM/set_point/sp/sx"]
blueprint = "blueprints/driver.rbl"
queue_size = 1

[rerunner_ego_state]
sub_topic = ["ego_state","ego_state_trajectory"]
time = "/timecode"
keypaths = ["/ego_state/ego_state/F_x", "/ego_state/ego_state/T", "/ego_state/ego_state/acceleration", "/ego_state/ego_state/angular_acceleration", "/ego_state/ego_state/angular_speed", "/ego_state/ego_state/space_linear", "/ego_state/ego_state/speed","/ego_state/ego_state/theta","/ego_state/ego_state/time_interval","/ego_state/ego_state/x","/ego_state/ego_state/y", "/ego_state_trajectory/trajectory/0", "/ego_state_trajectory/trajectory/1", "/ego_state_trajectory/trajectory/2"]
trace_keypaths = ["/ego_state_trajectory/trajectory"]
queue_size = 1
blueprint = "blueprints/ego_state.rbl" # local or absolute path to a valid blueprint

[calculate_torque]
sub_topic = ["driver"]
torque_current_ratio = 0.6

[driver_response]
sub_topic = ["FSM/set_point", "driver", "calculated_torque"] 
time = "/timecode"       # Name of the timecode column in the input data (s>
# List of keypaths for time series
keypaths = ["/FSM/set_point/sp/sx", "/FSM/set_point/sp/dx", "/driver/currents/left", "/driver/currents/right",  "/calculated_torque/torque/right_calculated", "/calculated_torque/torque/left_calculated"]
#acf_keypaths = ["/encoders/right", "/encoders/left"]
# winddow_size  = 200          # Width of the ACF and FFT window (int>
blueprint = "blueprints/driver_response.rbl" # local or absolute path to a valid bl>
queue_size=1