[broker]
command = "mads broker -d --crypto=broker --keys_dir=../visualization/keys/ --room=Novawalk"
workdir = ""
tty = "false"

[driver]
command = "mads filter driver --crypto --key_broker=broker --key_client=broker --keys_dir=../visualization/keys/"
workdir = ""
tty = "false"

[loadcells]
command = "mads source loadcells --crypto --key_broker=broker --key_client=broker --keys_dir=../visualization/keys/"
workdir = ""
tty = "false"

[portenta]
command = "mads sink portenta --crypto --key_broker=broker --key_client=broker --keys_dir=../visualization/keys/"
workdir = ""
tty = "false"

[forces_calibration]
command = "mads filter forces_calibration --crypto --key_broker=broker --key_client=broker --keys_dir=../visualization/keys/"
workdir = ""
tty = "false"

[imu_calibration]
command = "mads filter imu_calibration --crypto --key_broker=broker --key_client=broker --keys_dir=../visualization/keys/"
workdir = ""
tty = "false"

[imu]
command = "mads source sense-hat --crypto --key_broker=broker --key_client=broker --keys_dir=../visualization/keys/"
workdir = ""
tty = "false"

[ego_state]
command = "mads filter ego_state --crypto --key_broker=broker --key_client=broker --keys_dir=../visualization/keys/"
workdir = ""
tty = "false"

[unhookdetector]
command = "mads filter unhookdetector --crypto --key_broker=broker --key_client=broker --keys_dir=../visualization/keys/"
workdir = ""
tty = "false"

[watchdog]
command = "mads source watchdog --crypto --key_broker=broker --key_client=broker --keys_dir=../visualization/keys/"
workdir = ""
tty = "false"

[overload_detector]
command = "mads filter overload_detector --crypto --key_broker=broker --key_client=broker --keys_dir=../visualization/keys/"
workdir = ""
tty = "false"

[FSM]
command = "exec $(mads -p)/bin/mads-NovaWalk-FSM --crypto --key_broker=broker --key_client=broker --keys_dir=../visualization/keys/"
workdir = ""
tty = "false"



